# Generated by Django 3.0.5 on 2020-04-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='comment',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
